version: "3.9"


services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    working_dir: /code
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=db
      - DJANGO_DB_USER=postgres
      - DJANGO_DB_PASSWORD=postgres
    restart: always
  
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
  redis:
    image: redis:latest
    restart: always
  
  worker:
    build: .
    command: celery -A credit_approval_system worker --loglevel=info
    volumes: 
      - .:/code
    depends_on:
      - db
      - redis
    environment:
      DJANGO_DB_HOST: db
      DJANGO_DB_PORT: 5432
      DJANGO_DB_NAME: db
      DJANGO_DB_USER: postgres
      DJANGO_DB_PASSWORD: postgres
    restart: always

volumes:
  postgres_data: