# Generated by Django 5.2.4 on 2025-08-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customer_credit_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='current_debt',
            field=models.IntegerField(default=0),
        ),
    ]
